### ISSUE TITLE
MPOrderedDictionary不存在

### ISSUE THREAD

**Issue by ctsihhj** [FootballAddicts/msgpack-objc#1]
我需要使用排序的字典,按照官网样例使用
MPOrderedDictionary *dict = [[MPOrderedDictionary alloc] init];
[dict addEntriesFromDictionary:@{@"c": @(1), @"b": @(2), @"a": @(3)}];
[dict sortKeysUsingSelector:@selector(localizedCaseInsensitiveCompare:)];
[dict mp_messagePack];
MPOrderedDictionary类不存在,应该怎么解决?

**Comment by joelekstrom** [comment]
Hi! This functionality exists in more advanced implementations, for example https://github.com/gabriel/MPMessagePack.

It is not in the scope in this project. If you want to sort values, you could just convert them to an array first, for example.
